    - name: Build Release APK
      # Debug yerine Release komutu ve RAM düzenlemesi
      run: ./gradlew assembleRelease -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: EarBalance-Release-APK
        # Yol 'release' olarak güncellendi
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
